#!/bin/bash

# Close all open windows
hyprctl clients -j | \
  jq -r ".[].address" | \
  xargs -I{} hyprctl dispatch closewindow address:{}

# Small delay to let apps save state (e.g., browser sessions)
sleep 1

# Move to first workspace
hyprctl dispatch workspace 1
